#!/usr/bin/env bash

set -u
set -e

rm -rf activate .env

virtualenv --no-site-packages .env

ln -s .env/bin/activate activate

set +u
source activate
set -u

easy_install --upgrade pip

pip install pysnmp
